<?php

declare(strict_types=1);

namespace ApiPosture\Output;

use ApiPosture\Core\Model\Endpoint;
use ApiPosture\Core\Model\Finding;
use ApiPosture\Core\Model\ScanResult;
use ApiPosture\Core\Model\Enums\Severity;

final class MarkdownFormatter implements OutputFormatterInterface
{
    public function format(ScanResult $result, array $options = []): string
    {
        $lines = [];

        $lines[] = '# ApiPosture Scan Results';
        $lines[] = '';
        $lines[] = "**Scanned Path:** `{$result->scannedPath}`  ";
        $lines[] = sprintf("**Duration:** %.2fs  ", $result->duration);
        $lines[] = "**Files Scanned:** " . count($result->scannedFiles) . "  ";
        $lines[] = "**Endpoints Found:** " . count($result->endpoints) . "  ";
        $lines[] = "**Findings:** " . count($result->findings);
        $lines[] = '';

        // Severity breakdown
        if (!empty($result->findings)) {
            $lines[] = '## Findings Summary';
            $lines[] = '';
            $lines[] = '| Severity | Count |';
            $lines[] = '|----------|-------|';

            $severityCounts = $this->countBySeverity($result->findings);
            foreach ($severityCounts as $severity => $count) {
                $lines[] = "| {$severity} | {$count} |";
            }
            $lines[] = '';
        }

        // Endpoints table
        if (!empty($result->endpoints)) {
            $lines[] = '## Endpoints';
            $lines[] = '';
            $lines[] = '| Route | Methods | Classification | Controller | Auth |';
            $lines[] = '|-------|---------|----------------|------------|------|';

            foreach ($result->endpoints as $endpoint) {
                $methods = $endpoint->methodsString();
                $classification = $endpoint->classification->label();
                $controller = $endpoint->controllerName ?? '-';
                $auth = $endpoint->authorization->hasAuth ? 'Yes' : 'No';
                $lines[] = "| `{$endpoint->route}` | {$methods} | {$classification} | {$controller} | {$auth} |";
            }
            $lines[] = '';
        }

        // Findings detail
        if (!empty($result->findings)) {
            $lines[] = '## Findings Detail';
            $lines[] = '';

            foreach ($result->findings as $i => $finding) {
                $num = $i + 1;
                $icon = $this->severityIcon($finding->severity);
                $lines[] = "### {$num}. {$icon} [{$finding->ruleId}] {$finding->ruleName}";
                $lines[] = '';
                $lines[] = "**Severity:** {$finding->severity->label()}  ";
                $lines[] = "**Route:** `{$finding->endpoint->route}`  ";
                $lines[] = "**Location:** `{$finding->endpoint->location}`";
                $lines[] = '';
                $lines[] = $finding->message;
                $lines[] = '';
                if (!empty($finding->recommendation)) {
                    $lines[] = "> **Recommendation:** {$finding->recommendation}";
                    $lines[] = '';
                }
            }
        }

        if (!empty($result->failedFiles)) {
            $lines[] = '## Failed Files';
            $lines[] = '';
            foreach ($result->failedFiles as $file) {
                $lines[] = "- `{$file}`";
            }
            $lines[] = '';
        }

        $lines[] = '---';
        $lines[] = '*Generated by ApiPosture*';

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param Finding[] $findings
     * @return array<string, int>
     */
    private function countBySeverity(array $findings): array
    {
        $counts = [];
        foreach (Severity::cases() as $severity) {
            $count = count(array_filter($findings, fn(Finding $f) => $f->severity === $severity));
            if ($count > 0) {
                $counts[$severity->label()] = $count;
            }
        }
        return $counts;
    }

    private function severityIcon(Severity $severity): string
    {
        return match ($severity) {
            Severity::Critical => '🔴',
            Severity::High => '🟠',
            Severity::Medium => '🟡',
            Severity::Low => '🔵',
            Severity::Info => 'ℹ️',
        };
    }
}
